# Boolean Marsking

CS_Dojo [youtube](https://www.youtube.com/watch?v=r526yum0EYQ&index=11&list=PLBZBJbE_rGRWeh5mIBhD-hhDwSEDxogDg) [code](https://www.csdojo.io/python11)

# np.ndarray comparison works componentwise

In [1]:
import numpy as np

print(np.array([3, 7]) < 5)       # [ True  False ]
print(np.array([3, 7]) != 5)      # [ True  True  ]
print(np.array([3, 7]) == 5)      # [ False False ]
print(np.array([3, 7]) >= 5)      # [ False True  ]

[ True False]
[ True  True]
[False False]
[False  True]


# how to change np.ndarray data type

In [2]:
print(int(3.14)) # int is for int type

3


In [3]:
try:
    print(int([3.14, 1.7])) # int is for int type, not list type
except:
    pass

In [4]:
try:
    print(int(np.array([3.14, 1.7]))) # int is for int type, not np.ndarray type
except:
    pass

In [5]:
# count number of positive elements

import numpy as np

np.random.seed(337)

a = np.random.normal(0.,1.,(10,))
print(a)
print()

print(a>0)
print(type(a>0))
print()

# print(int(a>0)) # not working - int is for int type, not np.ndarray type
print((a>0).astype(np.int32))
print(type((a>0).astype(np.int32)))
print()

print(np.sum((a>0).astype(np.int32)))

[-0.44670457  0.38671228 -0.6046761   0.09101661 -1.53086331  0.25708252
 -1.1068968  -1.59140742  0.50642846 -0.69957044]

[False  True False  True False  True False False  True False]
<class 'numpy.ndarray'>

[0 1 0 1 0 1 0 0 1 0]
<class 'numpy.ndarray'>

4


In [6]:
import numpy as np

print(dir(np.ndarray))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmatmul__', '__rmod__', '__rmul__', 

# np.ndarray methods - sum, any, all

In [7]:
import numpy as np

np.random.seed(337)

a = np.random.normal(0.,1.,(10,))
print(a)
print()

print((a > 0).sum())             # counts number of positive values
print((a > 0).any())             # checks if any value is True
print((a > 0).all())             # checks if all values are True

[-0.44670457  0.38671228 -0.6046761   0.09101661 -1.53086331  0.25708252
 -1.1068968  -1.59140742  0.50642846 -0.69957044]

4
True
False


# boolean marsking

In [8]:
import numpy as np

np.random.seed(337)

a = np.random.normal(0.,1.,(10,))

print(a)
print()

print(a[a>0])
print()

print(np.sum(a[a>0]))

[-0.44670457  0.38671228 -0.6046761   0.09101661 -1.53086331  0.25708252
 -1.1068968  -1.59140742  0.50642846 -0.69957044]

[0.38671228 0.09101661 0.25708252 0.50642846]

1.241239868100609


In [9]:
# coin flip

import numpy as np

# fix the seed
np.random.seed(337)

# probability of head when we flip a coin
p = 0.5

# number of flips
n = 10

uniform_flip = np.random.uniform(0.,1.,(n,))
print(uniform_flip)
print()

coin_flip = np.zeros_like(uniform_flip).astype(np.int32)
print(coin_flip)
print()

coin_flip[uniform_flip>1-p] = 1        
print(coin_flip)

[0.79990679 0.15356741 0.5677806  0.04969421 0.54533612 0.23003453
 0.33956951 0.38841324 0.16388442 0.74331859]

[0 0 0 0 0 0 0 0 0 0]

[1 0 1 0 1 0 0 0 0 1]
