# Functions

CS_Dojo [youtube](https://www.youtube.com/watch?v=NSbOtYzIQI0&t=64s) [code](https://www.csdojo.io/python3)
Corey_Schafer [youtube](https://www.youtube.com/watch?v=9Os0o3wzS_I&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=8)

<a href="#Function-Object">Function Object</a>

<a href="#함수는-보통-인풋을-받아서-아웃풋을-만들어-낸다">함수는 보통 인풋을 받아서 아웃풋을 만들어 낸다</a>

<a href="#함수가-아웃풋이-없는-경우도-있다">함수가 아웃풋이 없는 경우도 있다</a>

<a href="#함수가-인풋이-없는-경우도-있다">함수가 인풋이 없는 경우도 있다</a>

<a href="#out-keyword">out keyword</a>

# Function Object

In [21]:
def f():
    pass

# 괄호가 없이 함수를 부르면 함수 자체를 부르게 된다.
print(f)
print()

# 괄호를 붙여 함수를 부르면 함수가 실행되어 함수의 리턴 값이 리턴된다. 
# 리턴 값이 없으므로 None이 리턴된다.
print(f())

<function f at 0x10f67e488>

None


[<a href="#Functions">Back to top</a>]

# 함수는 보통 인풋을 받아서 아웃풋을 만들어 낸다

In [23]:
def f(a, b, c):
    return a * b + c

# 괄호가 없이 함수를 부르면 함수 자체를 부르게 된다.
print(f)
print()

print(f(1, 2, 3))
print()

# 이 함수의 경우 인풋의 순서가 중요한다. 
# 이러한 인풋을 positional argument라고 한다.
print(f(3, 2, 1))
print()

# 인풋 갯수가 맞지 않으면 에러가 발생한다.
try:
    print(f(3, 2))
except Exception as e:
    print(e)

<function f at 0x10f67ebf8>

5

7

f() missing 1 required positional argument: 'c'


[<a href="#Functions">Back to top</a>]

# 함수가 아웃풋이 없는 경우도 있다

In [3]:
def f(a, b, c):
    print(a * b + c) 
    
# 괄호가 없이 함수를 부르면 함수 자체를 부르게 된다.
print(f)
print()

# 리턴 값이 없으므로 None이 리턴된다.
print(f(1, 2, 3))

<function f at 0x10f67e488>

5
None


[<a href="#Functions">Back to top</a>]

# 함수가 인풋이 없는 경우도 있다

In [4]:
def f():
    a = 1
    b = 2
    c = 3
    print(a * b + c) 
    
print(f)
print(f())

<function f at 0x10f67e730>
5
None


In [5]:
a = 4
b = 5
c = 6

def f(): 
    print(a * b + c) 
    
print(f)
print(f())

<function f at 0x10f67e840>
26
None


LEGB

L - Local
E - Enclosed
G - Global
B - Built-in

[<a href="#Functions">Back to top</a>]

# out keyword

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:

Python Data Science Handbook by Jake Vanderplas [github](https://github.com/jakevdp/PythonDataScienceHandbook) 

In [24]:
import numpy as np

x = np.arange(5) # [0 1 2 3 4]
y = np.empty(5)
print(y)
print()

np.multiply(x, 10, out=y)
print(y)

[ 1.  2.  4.  8. 16.]

[ 0. 10. 20. 30. 40.]


In [31]:
import numpy as np

x = np.arange(5) # [0 1 2 3 4]
y = np.zeros(10)
print(y)
print()

np.power(2, x, out=y[::2])
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


[<a href="#Functions">Back to top</a>]

### Example

In [8]:
def is_leap(year):
    """Return True for leap years, False for non-leap years."""
    return year % 4 == 0 and ( year % 100 != 0 or year % 400 == 0)

In [9]:
is_leap(2017)

False

In [10]:
is_leap(2020)

True

In [11]:
def days_in_month(year, month):
    """Return number of days in that month in that year."""
    
    month_days = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    
    if not 1<= month <= 12:
        return 'Invalid Month'
    
    if month == 2 and is_leap(year):
        return 29
    else:
        return month_days[month] 

In [12]:
days_in_month(2017, 2)

28

In [13]:
days_in_month(2020, 3)

31

[<a href="#Functions">Back to top</a>]

### Exercise

Exercise. Find all primes up to $n$ when $n$ is given.

In [14]:
# https://github.com/joeyajames/Python/blob/master/Primes.py
# prime number calculator: find all primes up to n

max = int(input("Find primes up to what number? : "))
primeList = []

for x in range(2, max + 1):
    isPrime = True
    index = 0
    root = int(x ** 0.5) + 1
    
    while index < len(primeList) and primeList[index] <= root:
        if x % primeList[index] == 0:
            isPrime = False
            break
        index += 1
            
    if isPrime:
        primeList.append(x)
        
print(primeList)

Find primes up to what number? : 10
[2, 3, 5, 7]


In [15]:
# https://github.com/joeyajames/Python/blob/master/Primes.py
# modified from original code
# max is a reserved word
# original variable name : max
# modified variable name : max_bound

# prime number calculator: find all primes up to n

max_bound = int(input("Find primes up to what number? : "))
primeList = []

for x in range(2, max_bound + 1):
    isPrime = True
    index = 0
    root = int(x ** 0.5) + 1
    
    while index < len(primeList) and primeList[index] <= root:
        if x % primeList[index] == 0:
            isPrime = False
            break
        index += 1
            
    if isPrime:
        primeList.append(x)
        
print(primeList)

Find primes up to what number? : 10
[2, 3, 5, 7]


Exercise. Find the first $n$ primes when $n$ is given.

In [16]:
# https://github.com/joeyajames/Python/blob/master/Primes.py

count = int(input("Find how many primes?: "))
primeList = []
x = 2

while len(primeList) < count:
    isPrime = True
    index = 0
    root = int(x ** 0.5) + 1

    while index < len(primeList) and primeList[index] <= root:
        if x % primeList[index] == 0:
            isPrime = False
            break
        index += 1

    if isPrime:
        primeList.append(x)

    x += 1

print(primeList)

Find how many primes?: 10
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


[<a href="#Functions">Back to top</a>]

연습문제.
짝수면 True, 홀수면 False를 리턴하는 다음 함수를 완성하시오.

```
def even(integer):
    ### put your code below
    if ### put your code here
    ### put your code above
        return True
    else:
        return False

print(even(2))
```

In [17]:
def even(integer):
    ### put your code below
    if integer % 2 == 0:
    ### put your code above
        return True
    else:
        return False

print(even(10))

True
