In [5]:
a = [1,2,3]
b = [1,2,3]
print(a == b) # a와 b가 같은 데이터를 가지고 있는가?
print(a is b) # a와 b가 같은 오브젝트인가?
print(id(a) == id(b)) # a와 b가 같은 오브젝트 indentifier number를 가지고 있는가?
print(id(a))
print(id(b))

True
False
False
140364501197360
140364500967584


In [8]:
a = (1,2,[1,2,3]) 
b = (1,2,[1,2,3]) 
print(a == b) # a와 b가 같은 데이터를 가지고 있는가?
print(a is b) # a와 b가 같은 오브젝트인가?
print(id(a) == id(b)) # a와 b가 같은 오브젝트 indentifier number를 가지고 있는가?
print(id(a))
print(id(b))

True
False
False
140365039093632
140365039092912


In [9]:
a = {'Calculus', 'Algebra'}
b = {'Calculus', 'Algebra'}
print(a == b) # a와 b가 같은 데이터를 가지고 있는가?
print(a is b) # a와 b가 같은 오브젝트인가?
print(id(a) == id(b)) # a와 b가 같은 오브젝트 indentifier number를 가지고 있는가?
print(id(a))
print(id(b))

True
False
False
140365039102384
140365039102864


In [10]:
a = {'one' : 1, 'two' : 2, 'three' : 3}
b = {'one' : 1, 'two' : 2, 'three' : 3}
print(a == b) # a와 b가 같은 데이터를 가지고 있는가?
print(a is b) # a와 b가 같은 오브젝트인가?
print(id(a) == id(b)) # a와 b가 같은 오브젝트 indentifier number를 가지고 있는가?
print(id(a))
print(id(b))

True
False
False
140364770205040
140364770205200


In [11]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a == b) # a와 b가 같은 데이터를 가지고 있는가?
print(a is b) # a와 b가 같은 오브젝트인가?
print(id(a) == id(b)) # a와 b가 같은 오브젝트 indentifier number를 가지고 있는가?
print(id(a))
print(id(b))

[ True  True  True]
False
False
140364770198432
140365303752464


# aliasing

In [1]:
a = [1,2,3] 
b = a       
print(a)
print(b)
print('-'*50)

b[-1] = 300
print(a) # aliasing
print(b) # aliasing

[1, 2, 3]
[1, 2, 3]
--------------------------------------------------
[1, 2, 300]
[1, 2, 300]


In [3]:
a = [1,2,3] 
b = [1,2,3] 
print(a)
print(b)
print('-'*50)

b[-1] = 300
print(a) # no aliasing
print(b) # no aliasing

[1, 2, 3]
[1, 2, 3]
--------------------------------------------------
[1, 2, 3]
[1, 2, 300]


In [6]:
a = (1,2,[1,2,3]) 
b = a             
print(a)
print(b)
print('-'*50)

b[-1][-1] = 300
print(a) # aliasing
print(b) # aliasing

(1, 2, [1, 2, 3])
(1, 2, [1, 2, 3])
--------------------------------------------------
(1, 2, [1, 2, 300])
(1, 2, [1, 2, 300])


In [7]:
a = (1,2,[1,2,3]) 
b = (1,2,[1,2,3]) 
print(a)
print(b)
print('-'*50)

b[-1][-1] = 300
print(a) # no aliasing
print(b) # no aliasing

(1, 2, [1, 2, 3])
(1, 2, [1, 2, 3])
--------------------------------------------------
(1, 2, [1, 2, 3])
(1, 2, [1, 2, 300])


In [12]:
a = {'Calculus', 'Algebra'} 
b = a             
print(a)
print(b)
print('-'*50)

b.remove('Algebra')
print(a) # aliasing
print(b) # aliasing

{'Calculus', 'Algebra'}
{'Calculus', 'Algebra'}
--------------------------------------------------
{'Calculus'}
{'Calculus'}


In [13]:
a = {'Calculus', 'Algebra'} 
b = {'Calculus', 'Algebra'}              
print(a)
print(b)
print('-'*50)

b.remove('Algebra')
print(a) # no aliasing
print(b) # no aliasing

{'Calculus', 'Algebra'}
{'Calculus', 'Algebra'}
--------------------------------------------------
{'Calculus', 'Algebra'}
{'Calculus'}


In [14]:
a = {'one' : 1, 'two' : 2, 'three' : 3} 
b = a             
print(a)
print(b)
print('-'*50)

del b['three']
print(a) # aliasing
print(b) # aliasing

{'one': 1, 'two': 2, 'three': 3}
{'one': 1, 'two': 2, 'three': 3}
--------------------------------------------------
{'one': 1, 'two': 2}
{'one': 1, 'two': 2}


In [15]:
a = {'one' : 1, 'two' : 2, 'three' : 3} 
b = {'one' : 1, 'two' : 2, 'three' : 3}             
print(a)
print(b)
print('-'*50)

del b['three']
print(a) # no aliasing
print(b) # no aliasing

{'one': 1, 'two': 2, 'three': 3}
{'one': 1, 'two': 2, 'three': 3}
--------------------------------------------------
{'one': 1, 'two': 2, 'three': 3}
{'one': 1, 'two': 2}


In [16]:
import numpy as np

a = np.array([1,2,3]) 
b = a                 
print(a)
print(b)
print('-'*50)

b[-1] = 300
print(a) # aliasing
print(b) # aliasing

[1 2 3]
[1 2 3]
--------------------------------------------------
[  1   2 300]
[  1   2 300]


In [17]:
import numpy as np

a = np.array([1,2,3]) 
b = np.array([1,2,3]) 
print(a)
print(b)
print('-'*50)

b[-1] = 300
print(a) # no aliasing
print(b) # no aliasing

[1 2 3]
[1 2 3]
--------------------------------------------------
[1 2 3]
[  1   2 300]


# shallow copy

In [20]:
import copy

a = [1,2,3]

# In this case, a and b are pointing the same list object.
# b = a 

# In this case, [1,2,3] is copied.
# a is pointing the original list, whereas
# b is pointing the copied list
#b = a 
#b = a[:] # shallow copy
b = copy.copy(a) # shallow copy
print(a)
print(b)
print('-'*50)

b[-1] = 300
print(a)
print(b)

[1, 2, 3]
[1, 2, 3]
--------------------------------------------------
[1, 2, 3]
[1, 2, 300]


In [24]:
import numpy as np
import copy

a = np.array([1,2,3])

# In this case, a and b are pointing the same np array object.
#b = a 

# In this case, np.array([1,2,3]) is copied.
# a is pointing the original np array, whereas
# b is pointing the copied np array.
#b = a.copy()    # shallow copy
#b = np.copy(a)  # shallow copy
b = copy.copy(a) # shallow copy
print(a)
print(b)
print('-'*50)

b[-1] = 300
print(a)
print(b)

[1 2 3]
[1 2 3]
--------------------------------------------------
[1 2 3]
[  1   2 300]


In [29]:
import copy

a = [1,2,[1,2,3]]
#b = a # aliasing
#b = a[:] # shallow copy (aliasing)
#b = copy.copy(a) # shallow copy (aliasing)
b = copy.deepcopy(a) # deep copy (no aliasing)
print(a)
print(b)
print('-'*50)

b[-1][-1] = 300
print(a)
print(b)

[1, 2, [1, 2, 3]]
[1, 2, [1, 2, 3]]
--------------------------------------------------
[1, 2, [1, 2, 3]]
[1, 2, [1, 2, 300]]
