In [18]:
a = 1
b = 1
c = a + b
print(c)
print(type(a), type(b), type(c))

2
<class 'int'> <class 'int'> <class 'int'>


In [19]:
a = 1.
b = 1.
c = a + b
print(c)
print(type(a), type(b), type(c))

2.0
<class 'float'> <class 'float'> <class 'float'>


In [20]:
a = '1'
b = '1'
c = a + b
print(c)
print(type(a), type(b), type(c))

11
<class 'str'> <class 'str'> <class 'str'>


In [21]:
a = [1,2,3]
b = [4,5,6]
c = a + b
print(a)
print(b)
print(c)
print(type(a), type(b), type(c))

[1, 2, 3]
[4, 5, 6]
[1, 2, 3, 4, 5, 6]
<class 'list'> <class 'list'> <class 'list'>


In [12]:
import numpy as np

In [13]:
import pandas as pd

In [14]:
import matplotlib.pyplot as plt

In [15]:
from sklearn.linear_model import LinearRegression

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(a)
print(b)
print(c)
print(type(a), type(b), type(c))

[1 2 3]
[4 5 6]
[5 7 9]
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [25]:
class OnePlusOne:
    
    def __init__(self, string):
        self.string = string
        
    def __add__(self, other):
        if (self.string=='1') and (other.string=='1'):
            return '일더하기 일은 귀요미'
        
a = OnePlusOne('1')
b = OnePlusOne('1')
c = a + b

print(c)
print(type(a), type(b), type(c))

일더하기 일은 귀요미
<class '__main__.OnePlusOne'> <class '__main__.OnePlusOne'> <class 'str'>
