In [57]:
a = [3., 3., 7., 'one', 'two', 'three']

In [38]:
a = (3., 3., 7., 'one', 'two', 'three')
a[0] = 'zero' # tuple - immutable

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


In [19]:
a = {3, 3, 7, 'one', 'two', 'three'}
print(a)

{3, 7, 'two', 'three', 'one'}


In [21]:
a = {'one': 3., 'two': 3., 'three': 7.} # {key: value, ...}
print(a['two'])
print(type(a['two']))

3.0
<class 'float'>


In [51]:
a = []
print(a)

for i in range(10):
    a.append(i)
    print(a)
    
for i in range(10):
    a.pop(0)
    print(a)

[]
[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]
[]


In [61]:
import numpy as np
a = np.eye(6,9).astype(np.int32) # Method or Attribute?
print(a)
print(a.shape) # Method or Attribute?
print(a.dtype) # Method or Attribute?

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]]
(6, 9)
int32


In [73]:
import numpy as np
a = np.eye(6,9).astype(np.int32) # 6-by-9 matrix
b = np.random.normal(size=(9, 6)) # 9-by-6 matrix
print((a@b).dtype) # __matmul__ dunder method
print((a.dot(b)).dtype) # dot method
print(np.matmul(a,b).dtype) # np function

float64
float64
float64


In [74]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_