# Intro

Clever_Programmer [youtube](https://www.youtube.com/watch?v=f3EbDbm8XqY)
Joe_James 
[youtube](https://www.youtube.com/watch?v=5CZvkggt7C4) 
[github](https://github.com/joeyajames/Python)
codebasics
[youtube](https://www.youtube.com/watch?v=eykoKxsYtow)

# Top 5 Reasons to Learn Python

> 5 Dynamically Typed

> 4 Simple Syntax

> 3 One Liners

> 2 English-like Commands

> 1 Intuitive Data Structures

In [16]:
a = 1
b = 1
print(type(a+b))
print(a+b)
print(dir(a))

<class 'int'>
2
['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


In [7]:
a = 1.
b = 1.
print(type(a+b))
print(a+b)

<class 'float'>
2.0


In [8]:
a = '1'
b = '1'
print(type(a+b))
print(a+b)

<class 'str'>
11


In [10]:
a = [1,2,3]
b = [4,5,6]
c = a + b
print(a)
print(b)
print(c)

[1, 2, 3]
[4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [12]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[5 7 9]


In [17]:
class OnePlusOne:
    
    def __init__(self, string):
        self.string = string
        
    def __add__(self, other):
        if (self.string=='1') and (other.string=='1'):
            return '일더하기 일은 귀요미'
        
a = OnePlusOne('1')
b = OnePlusOne('1')
c = a + b

print(a)
print(b)
print(c)
#print(type(a), type(b), type(c))
print(dir(a))

일더하기 일은 귀요미
['__add__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'string']
