In [1]:
a = [1,2,2] # list
b = (1,2,2) # tuple
c = {1,2,2} # set
d = {'one':1, 'two':2, 'three':2} # dic

In [3]:
print(dir(a))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [4]:
print(dir(b))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


In [5]:
print(dir(c))

['__and__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [6]:
print(dir(d))

['__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
a = np.array([[1,2,3],[2,3,4]])
print(a, type(a))

[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'>


In [5]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [88]:
a = np.array([[1,2,3],[2,3,4]], dtype=np.int32) # a = (a_{ij})
print(a, type(a))

[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'>


In [11]:
print(a.shape, type(a.shape))

(2, 3) <class 'tuple'>


In [89]:
print(a.dtype, type(a.dtype))

int32 <class 'numpy.dtype'>


In [24]:
# a.shape # 변수 ---- 어트리뷰트 
# a.dtype # 변수 ---- 어트리뷰트  
print(a.cumprod()) # 함수 ---- 메쏘드

[  1   2   6  12  36 144]


In [29]:
class Student():
    
    def __init__(self, name, subject, gender, salary):
        self.name = name
        self.subject = subject
        self.gener = gender
        self.salary = salary  
        
    def raise_salary(self, amount):
        self.salary += amount
        
    def add(self, item):
        if item not in self.subject: 
            self.subject += [item]
            
    def drop(self, item):
        try:
            self.subject.remove(item) 
        except:
            print(f'{self.name}, {item} 수강리스트에 없어요. 정신 차리세요.')

In [30]:
a = Student('박성준', 
            ['통계학', '정수론', '고전역학', '선형대수2'], 
            '남자',
            15_000_000)
a.drop('미적2')
a.subject

박성준, 미적2 수강리스트에 없어요. 정신 차리세요.


['통계학', '정수론', '고전역학', '선형대수2']

In [76]:
b = Student('최유진', 
            ['통계학', '해석학', '전자기학', '경재학원론'], 
            '여자',
            10_000_000)

In [79]:
a.salary

15000000

In [77]:
b.subject

['통계학', '해석학', '전자기학', '경재학원론']

In [63]:
b = Student('최유진', 
            ['통계학', '해석학', '전자기학', '경재학원론'], 
            '여자',
            10_000_000)
print(b.name)

AttributeError: 'Student' object has no attribute 'name'